### ISSUE TITLE
Specifying an intercept as a fixed effect.

### ISSUE THREAD

**Issue by g-morishita** [DejanDraschkow/mixedpower#10]
Hey team!

Thank you for creating a very useful library – it's been a huge help! 

I'm curious, though, is there any way to set the intercept as a fixed effect? Right now, I'm trying to figure out the required sample size to check if an intercept is not zero.  If you have already covered this in the documentation, my apologies for overlooking it.

Thanks again for all your hard work on this project.

Best regards,

**Comment by lkumle** [comment]
Hi, 

thanks for getting in touch! As of now, mixedpower does not allow to include the intercept in the power simulations. 

We will let you know in case this becomes available in a future version!
