### ISSUE TITLE
Having trouble storing simulations?

### ISSUE THREAD

**Issue by MalloryJfeldman** [DejanDraschkow/mixedpower#4]
HI! Every time I try to run simulations i'm getting this error:

Error in apply(store_simulations, MARGIN = 1, FUN = mean, na.rm = T) : 
  dim(X) must have a positive length

along with these warnings: In for (v in val) { ... : closing unused connection 16 (<-localhost:11941)

I'm confused because this package has worked fine for me in the past! Any help would be greatly appreciated!

**Comment by lkumle** [comment]
Hi! The error comes up whenever something in the simulation of new data sets goes wrong. This could have different reasons (e.g., a between-subject variable with missing values,  dublicates that result in mixedpower not being able to determine if a predictor is a between or within subject manipulation,...). If still helpful, I could have a look at your code and data. Feel free to reach out via email!

**Comment by ConnorEsterwood** [comment]
@lkumle I'm now having this issue too. Still OK with a direct email or message for some help on this?
