### ISSUE TITLE
Add option to specify the number of cores used

### ISSUE THREAD

**Issue by DanielEWeeks** [DejanDraschkow/mixedpower#7]
Looks like `mixedpower` by default uses all the available cores except one:

```
    cores = parallel::detectCores()
    cl <- parallel::makeCluster(cores[1] - 1)
    doParallel::registerDoParallel(cl)
```

As we have many users working on our computational cluster, it would be helpful if we could specify the maximum number of cores used.  

Thank you for considering this request.

**Comment by lkumle** [comment]
Hi, thanks for bringing this up! 

Both mixedpower() and R2power() now allow to specify the maximum number of cores through the maxCores argument:

```
mixedpower(model, data, fixed_effects, simvar,

           steps, critical_value, n_sim = 1000,

           SESOI = F, databased = T, maxCores = NULL)
```

If unspecified, simulations will run on all except one core.
